### ISSUE TITLE
Add auto scroll to top in App Interface

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#1]
The app interface does not scroll automatically when either the AI or the user provides a response. Consequently, it becomes challenging to determine whether the AI has given any response (I have to scroll manually for now).

So, we need to **implement a feature** that automatically scrolls the interface to the top whenever the user makes a request or the AI provides a response. This way, the most recent content becomes visible to the user.
  
_Directory of Javascript file of App Interface:_
> **UI/web/script.js**

https://github.com/rmondal-official/PINAC/assets/78198704/a188ac53-5c37-43b9-b43b-bd7973e202a5

**Comment by jeevikasirwani** [comment]
I can try to solve this and will revert back soon

**Comment by rmondal-official** [comment]
Thank you for being interested. I appreciate your effort in trying to solve this issue. I’ll be waiting for your update. Please let me know if you need any further information from my end

**Comment by rmondal-official** [comment]
**Hi Jeevika Sirwani**,

I wanted to express my heartfelt gratitude for the significant contributions you've made by solving this issue through your pull requests. Thank you for your valuable pull requests and contributions to our project! Your efforts are greatly appreciated.

Best,
**Rajesh Mondal**
