### ISSUE TITLE
Add animation while waiting for AI response

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#10]
Need to add animation in the chatbox of the app's interface while waiting for AI response(after the user asks any question). This will significantly improve user experience!

**Knock me if you need any help from my side**

**Comment by DanejSakshi13** [comment]
Hi there! I've reviewed the issue regarding the need to add an animation while waiting for the AI response. I'm confident that I can implement the required changes to address this issue effectively. Could you please assign this task to me? I'm eager to start working on it and provide a solution promptly. Thank you!

**Comment by rmondal-official** [comment]
**Hi Sakshi Danej**!

Thanks for taking a look at the animation for the AI response wait time. I'm confident you can tackle this and come up with a great solution. Therefore, I am assigning this enhancement task to you. I'm eager to see what you come up with!

Best,
**Rajesh Mondal**

**Comment by DanejSakshi13** [comment]
Thank you!
Apart from addressing the animation issue, I've also identified additional areas for improvement :
1. Clearing prompt input section after hitting the send button
2. Disabling the send button while AI is responding to the previous prompt 
3. Enhancing responsiveness

Could you please confirm if these contributions align with the project's direction?

**Comment by rmondal-official** [comment]
That's fantastic ! 

Absolutely, all the improvements you mentioned perfectly align with the project's direction. Regarding class/id names, feel free to update them to something more meaningful for better readability. Clear code makes maintenance easier for everyone in the future.

Let me know if you have any questions or need any help getting started.

**Comment by rmondal-official** [comment]
This enhancement is completed by @DanejSakshi13

**Comment by DanejSakshi13** [comment]
Thank you for accepting the pull request! I'm glad the changes were well received.
Looking forward to contributing more to the project in the future!
