### ISSUE TITLE
Redefine Light Theme

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#17]
Change the Colour tone of the light theme with a more **beautiful** and **modern-looking** (**glass effect**) colour combination.

**Comment by jeevikasirwani** [comment]
https://colorhunt.co/palette/eef5ffb4d4ff86b6f6176b87 ,u need these kinda background or glassmorphism?

**Comment by rmondal-official** [comment]
Yes, absolutely. Also with some Glass effect (if applicable) to make it look different and modern.

**Comment by rmondal-official** [comment]
Hey @jeevikasirwani, I really like the changes you made! However, I was thinking of adding a few more tweaks to make it even better. Hope you're okay with that !

**Comment by jeevikasirwani** [comment]
yup works
