### ISSUE TITLE
smoother sidebar 

### ISSUE THREAD

**Issue by jeevikasirwani** [rmondal-official/PINAC-Workspace#18]
smoother sidebar/menu that does not interrupts the logo and that has UI appealing background.

**Comment by rmondal-official** [comment]
Yes, it's a bug. The sidebar design is less responsive and needs improvement.

**Would you be interested in taking a look and seeing if you can fix it ?** I'd be happy to answer any questions you have.

**Comment by jeevikasirwani** [comment]
i will try
