### ISSUE TITLE
theme changes to dark even after light theme is selected

### ISSUE THREAD

**Issue by jeevikasirwani** [rmondal-official/PINAC-Workspace#20]
the user should be able to use light theme even after clicking light theme but it changes to dark automatically
https://github.com/rmondal-official/PINAC-Workspace/assets/83456541/41a0e394-f77a-4429-af57-31883a1df7c3

**Comment by rmondal-official** [comment]
Thank you for reporting this bug! 

I’ve started working to resolve the issue and committed to resolving it as soon as possible. Your feedback is invaluable, and I’ll keep you updated on the progress. If you have any further insights or questions, feel free to share them.

Once again, thank you for being an active contributor to our community! 🌟

**Comment by rmondal-official** [comment]
I have resolved this issue. Please let me know if you encounter any further problems.
