### ISSUE TITLE
Add Animation to Welcome Text 

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#23]
In our App Interface, we need to change the **Static welcome text to Dynamic** and add an **auto-typing animation** with multiple texts. The texts will be:
- Hello, how can I help you today ?
- Need to send an urgent email ?  I can assist you
- Stay at the top of your schedule with me !
- Have any question ? Just ask me

Need any help from me ? Feel free to ask !

**Comment by kinnam888** [comment]
Hi, @rmondal-official . Can you assign me this ? I would like to work on it.

**Comment by rmondal-official** [comment]
Hi @kinnam888 ,

Thank you for your interest in contributing to the project! 🌟

I've assigned you to the issue. Your insights and expertise will be invaluable, and we're excited to see your contributions.

Please feel free to reach out if you have any questions or need further clarification.

Happy coding!

Best,
**Rajesh Mondal**

**Comment by rmondal-official** [comment]
Yes, I am reviewing it

**Comment by rmondal-official** [comment]
Hello @kinnam888 ,

You did it nicely, but I think there was a little misunderstanding. I think I haven't made it clear, what I meant was that I want the first text to appear, then change and then the next text to appear animatedly. These will display all 4 texts one by one and then it will repeat from first.

**Comment by rmondal-official** [comment]
This enhancement is completed by @kinnam888 🎉
