### ISSUE TITLE
Displaying the Email-template on Email-Composer page

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#25]
**Currently, the specific email template given by AI in response to user queries is shown on the chat interface**. But now we have the email-composer box, therefore **we need to show this template on the composer box correctly**. The subject will be placed in the subject box and the rest body in the body box, for now recipient email will be blank by default.

You need to make changes in the `main.py` file, followed by `index.js` and `email-composer.js`. **Having any doubt about understanding this issue or the code, simply ask me !**

**Comment by saadahmed9** [comment]
Created a PR for this request, please check.

**Comment by rmondal-official** [comment]
**I have completed this enhancement 😊** 

> **NOTE**: 
>**1**. `email-composer.js` uses the `alert` function to show any error caused by user input, which will be changed in future for betterment.
>**2**. I have changed the response type not just to solve this Issue but also to consider future development and efficiency.

( **New Bug Arrived**: Chat doesn't show the previous conversation after pages once shift to `email-composer.html`, as coming back to the `index.html` page causes a reload which leads to this bug. 
It can be solved using _local Storage_. We will solve this issue later with upcoming updates )
