### ISSUE TITLE
Not able to sign up

### ISSUE THREAD

**Issue by saadahmed9** [rmondal-official/PINAC-Workspace#30]
After clicking sign-up button and granting access to gmail account, I can see the message "The authentication flow has completed. You may close this window." 
But after closing the above window, I can see my gmail account is still not connected as the signup button is still visible.
How to ensure sign up is successful?

**Comment by rmondal-official** [comment]
Hello, @saadahmed9  ,
Nice to see your interest in our Project. Well, your concern is absolutely right, **we have some issues with the Sigh Up button**. But as you are saying: _"The authentication flow has completed. You may close this window."_ that clearly means it's done !

For ensuring, go to `src/configs` and you will see `google_token.json`, if it's there that means your sign-up was completed successfully. Also, place your `.env` file (for openai key) in that folder.

Let me know if your Sign-Up is incomplete. Feel free to ask any further question!

**Comment by rmondal-official** [comment]
**I have fixed this bug, thanks again for reporting this bug.**
