### ISSUE TITLE
Add Sidebar

### ISSUE THREAD

**Issue by rmondal-official** [rmondal-official/PINAC-Workspace#7]
### Need to add a sidebar on the left side with buttons for shifting pages

Buttons that need to be added are:
- Profile
- New Chat
- About Us
  
Additionally, you can add any extra button in your mind. Feel free to modify the HTML and CSS structure to implement these changes. **If you need any help from my side, knock me**.

**Comment by artypratham** [comment]
Hello! I have gone through the issue regarding the need to add a sidebar on the left side with appropriate buttons for shifting through pages. I'm confident that I can implement the required changes to address the issue effectively & enhance the user experience. Could you please assign this task to me? I'm eager to start working on it and provide a solution promptly. Thank you!

**Comment by rmondal-official** [comment]
Hello,

Thank you for your enthusiasm! I’am assigning the task to you. Please proceed with implementing the sidebar changes. If you have any questions, feel free to ask.

**Comment by artypratham** [comment]
Thank you so much. I am on it!

**Comment by rmondal-official** [comment]
This enhancement is completed by @artypratham 🎉
